### ISSUE TITLE
Virus? what?

### ISSUE THREAD

**Issue by Suburbanno** [telmer6/lolpass2#1]
- Trojan.Reconyc.gnt 	
- Hacktool 
- Malware.Heuristic!ET#96% (rdm+)
- TrojanSpy.MSIL.Omaneat 

[Virustotal](https://www.virustotal.com/pt/file/bd19c90cd96e5e234ae0cfceaaa6b10457655a046e9225dfbf798c122714af0d/analysis/1496172400/)

**Comment by telmer6** [comment]
Uh, what? 
I'm going to guess that this is because of the hooks Auto Hot Key uses to send key commands, but I'll take a closer look when I get a chance.

**Comment by telmer6** [comment]
Or if you don't trust me (completely understandable), you can download AHK here: https://autohotkey.com/ and run the source code.

**Comment by Suburbanno** [comment]
oh ok, thanks

**Comment by telmer6** [comment]
Also, I just ran the latest release through VirusTotal using the URL on the release page, and got a clean result: https://www.virustotal.com/en/url/e75ff11a2d8087858708e1312ea78cfc737d0a4923a4b98baa12733aece7050e/analysis/1496175516/  
You may want to run a virus scan on your own system in case something else infected it...
